version: '3.0'
services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
      - "80:80"
    restart: always
    volumes:
      - wp_data:/home/lothieve/data
      - ./srcs/requirements/nginx/nginx-conf:/etc/nginx-conf
      - ./srcs/requirements/nginx/nginx.conf:/etc/nginx.conf
  mariadb:
    build: ./requirements/mariadb
    volumes:
      - db_data:/home/lothieve/data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    volumes:
      - wp_data:/home/lothieve/data
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_NAME}
volumes:
  db_data: {}
  wp_data: {}
