version: '3'
services:
  mysql:
    build: ./requirements/mariadb
    volumes:
      - /home/lothieve/data/db:/var/lib/mysql
      - ./requirements/mariadb/mariadb-server.cnf:/etc/my.cnf.d/mariadb-server.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
      MYSQL_DATABASE: inception
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    networks:
      - inception
    container_name: mysql
  wordpress:
    build: ./requirements/wordpress
    volumes:
      - /home/lothieve/data/wp:/var/www/html
      - ./requirements/wordpress/www.conf/:/etc/php7/php-fpm.d/www.conf
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
      WORDPRESS_DB_NAME: inception
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TABLE_PREFIX: wp_
    networks:
      - inception
    container_name: wordpress
    restart: always
  nginx:
    build: ./requirements/nginx/
    volumes:
      - ./requirements/nginx/conf/lothieve.conf:/etc/nginx/conf.d/lothieve.conf
      - /home/lothieve/data/wp:/var/www/html
    ports:
      - 443:443
    networks:
      - inception
    container_name: nginx

networks:
  inception:
